spring:
  # enable h2 console & set path
  h2:
    console:
      enabled: true
      path: /h2

  # h2 db properties
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # hibernate properties
    show_sql: true
    hibernate:
      ddl-auto: create
